apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: test
  labels:
    app: nginx
spec:
  nodeName: worker01
  containers:
  - name: nginx
    image: quay.io/ysachin/cilium/app:v1
    imagePullPolicy: Always
    securityContext:
      privileged: true
